name: "\U0001F41B Bug or Crash Report"
title: "bug: "
description: Unexpected behavior with StoneDB.
labels: ["A-bug"]
body:
  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines on issues?
      options:
        - label: I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).
          required: true
          
  - type: checkboxes
    attributes:
      label: Please confirm if bug report does NOT exists already ?
      description: We kindly ask that you [search](https://github.com/stoneatom/stonedb/issues?q=is%3Aissue+is%3Aclosed) to see if an issue already exists for your bug
      options:
        - label: I confirm there is no existing issue for this
          required: true

  - type: textarea
    attributes:
      label: Describe the problem
      placeholder: >
        Please describe the problem you observed.

  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: >
        Expected behavior you want to see.

  - type: textarea
    attributes:
      label: How To Reproduce
      placeholder: >
        Provide minimal steps to reproduce the behavior:

  - type: textarea
    attributes:
      label: Environment
      placeholder: >
        Please describe your environment.
        1. Server OS [e.g. Linux/MacOS/Distrib ...]
        2. StoneDB Version [e.g. 1.0.x]

  - type: checkboxes
    attributes:
      label: Are you interested in submitting a PR to solve the problem?
      description: >
        We are looking forward to working with you to make a better StoneDB community.
      options:
        - label: Yes, I will!

