module.exports = {
  'layout-header-height': '100px',
  'layout-footer-height': '133px',
  'layout-header-background': '#ffffff',
  'layout-body-background': '#ffffff',
  'text-color-dark': '#646A7D',
  'text-color-secondary-dark': '#CBCDD3',
  'text-color': '#373c43',
  'text-color-secondary': '#646A7D',
  'tooltip-bg': '#ffffff',
  'tooltip-color': '@text-color-secondary',
  'border-radius-base': '10px',
  'primary-color': '#00A6FB',
  'height-base': '40px',
  'height-lg': '65px',
  'input-bg': '#F2F3F7',
  'alert-info-bg-color': '#F2F3F7',
  'alert-text-color': 'text-color-dark',
  'menu-bg': 'transparent',
  'btn-default-bg': '#F2F3F7',
  'border-color-base': '#E5E8F0',
  'btn-default-color': '#646A7D',
  'btn-primary-bg': '#00A6FB',
  'select-border-color': 'transparent',
}
