 create table if not exists $table_name (
  `seller_id` bigint(20) DEFAULT NULL COMMENT '卖家ID',
  `feed_id` bigint(20) DEFAULT NULL COMMENT '主评ID',
  `feedback` text COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '主评内容',
  `gmt_create` datetime DEFAULT NULL COMMENT '主评时间',
  `pic_path` text COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '主评图片URL',
  `reply` text COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '主评解释',
  `append_feed_id` bigint(20) DEFAULT NULL COMMENT '追评ID',
  `append_feedback` text COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '追评内容',
  `append_pic_path` text COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '追评图片URL',
  `append_gmt_create` datetime DEFAULT NULL COMMENT '追评时间',
  `append_days` bigint(20) DEFAULT NULL COMMENT '差距天数',
  `append_reply` text COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '追评解释',
  `pushed_by` bigint(20) DEFAULT NULL COMMENT '推送原因',
  `item_id` bigint(20) DEFAULT NULL COMMENT '商品ID',
  `item_title` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '商品标题',
  `item_url` varchar(512) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '商品图标',
  `order_id` bigint(20) DEFAULT NULL COMMENT '订单编号',
  `anony` bigint(20) DEFAULT NULL COMMENT '是否匿名',
  `buyer_id` bigint(20) DEFAULT NULL COMMENT '买家ID',
  `buyer_nick` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '买家昵称',
  `buyer_star` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '买家星级',
  `keywords` varchar(1024) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '订阅词',
  `keywords_position` varchar(1024) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '订阅词标红位置',
  `gmt_modified` datetime DEFAULT NULL COMMENT '修改时间',
  `attributes` text COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '颜色+属性',
  `lock_version` bigint(20) DEFAULT NULL COMMENT '锁字段预留',
  KEY `index_seller_id` (`seller_id`),
  KEY `index_gmt_create` (`gmt_create`),
  KEY `index_gmt_modify` (`gmt_modified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
