name: Developing

on:
  push:
    branches-ignore:
      - main
    pull_request:
      paths-ignore:
        - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  PROTOC: protoc

jobs:
  stonedb-build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      
      - name: install prerequisites
        run: |
          sudo apt-get update
